### PR TITLE
added playlist generation

### PR DESCRIPTION
**Pull request by jb6131**
Added playlist generation for each genre button with an id of that genre

### CODE REVIEW

**Review by Chase-Garrett — CHANGES_REQUESTED** [review]
Keep a copy of the generated playlist separate from the function that generates it and ensure that it gets erased and loaded with new data with each search. This allows it to accessed for the video playlist generation as well as accessed by local storage.

**Comment by jb6131** [comment]
> Keep a copy of the generated playlist separate from the function that generates it and ensure that it gets erased and loaded with new data with each search. This allows it to accessed for the video playlist generation as well as accessed by local storage.

**Comment by jb6131** [comment]
Added the requested changes, changed the number of songs in the playlist to 30, and added a function and event listener for the "all" genre button.

**Review by Chase-Garrett — APPROVED** [review]
Looks good!

**Pull request merged**
